data_warehouse:
  outputs:
    dev:
      type: postgres
      dbname: "{{ env_var('dbcommodities_xl2f') }}"
      host: "{{ env_var('DB_HOST_PROD') }}"
      pass: "{{ env_var('DB_PASS_PROD') }}"
      port: "{{ env_var('DB_PORT_PROD') | int }}"
      schema: "{{ env_var('DB_SCHEMA_PROD') }}"
      threads: "{{ env_var('DB_THREADS_PROD') }}"
      user: "{{ env_var('DB_USER_PROD') | int }}"
      keeplives idle: 0
  target: dev
